name: CI/CD

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
          distribution: 'adopt'
          java-version: '17'
    - name: Compile
      run: |
        echo "Compiling the code"
        ./mvnw compile
    - name: Test
      run: |
        echo "Running the tests"
        ./mvnw test
    - name: Build image
      run: |
        echo "Building the image"
        docker build -t ${{ github.event.repository.name }}:latest .
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Push image to Docker Hub
      run: |
        echo "Pushing the image to Docker Hub"
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag myapp ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
    - name: Deploy
      run: |
        echo "Deploying the app"