name: CI-CD workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        echo "Compiling the code"
       ./mvnw clean install
    - name: Test
      run: |
        echo "Running the tests"
        ./mvnw test