name: Validate PR

concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
    - uses: amannn/action-semantic-pull-request@v5.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          fix
          feat
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
        requireScope: true
        disallowScopes: |
          release
        githubBaseUrl: ${{ github.api_url }}
        ignoreLabels: |
          bot